version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wedeome
    container_name: app
    restart: unless-stopped
    volumes:
        - ./:/var/www/wedeome

  webserver:
    build:
      context: .
      dockerfile: Dockerfile_Nginx
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/wedeome
      - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app

  db:
    image: mysql:8.0.23
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wedeome
      MYSQL_USER: wedeome
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8081:80"

volumes:
  dbdata:
    driver: local
